#!/usr/bin/env bash
# Transfer a file from client to server using scp

if [ $# -lt 3 ]
then
	echo "Usage: $(basename "$0") PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
elif [ $# -lt 4 ]
then
	PATH_TO_FILE=$1
	IP=$2
	USERNAME=$3
	PATH_TO_SSH_KEY="" # this parameter is optional; a default key is used if it is omitted
else
	PATH_TO_FILE=$1
	IP=$2
	USERNAME=$3
	PATH_TO_SSH_KEY=$4
fi

scp -i "$PATH_TO_SSH_KEY" -o StrictHostKeyChecking=no "$PATH_TO_FILE" "$USERNAME@$IP:~/"
