#!/usr/bin/env bash
# Configure nginx server with 301 redirection and custom 404 error message

if ! [ -x "$(command -v nginx)" ]; then
    apt update
    apt install -y nginx
fi

ufw allow "Nginx HTTP"
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/my_404.html
service nginx start

cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default_back_up

awk '
    {
        if ($0 == "\tserver_name _;") {
            print "\tserver_name _;"
            print "\tlocation ~ /redirect_me[/]?$ {"
            print "\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;"
            print "\t}\n"
			print "\terror_page 404 /my_404.html;"
			print "\tlocation = /my_404.html {"
			print "\t\troot /var/www/html;"
			print "\t\tinternal;"
			print "\t}"
        } else {
            print $0
        }
    }
' /etc/nginx/sites-available/default > temp && mv temp /etc/nginx/sites-available/default

service nginx restart
